library(testthat)
library(h2o)
library(foreach)
library(h2otest)

h2o::h2o.init()
h2o::h2o.no_progress()
set.seed(1)
old <- options(digits = 6)
test_check("h2otest")
options(old)
h2o::h2o.show_progress()
h2o::h2o.shutdown()
